### ISSUE TITLE
[UI Issue] : No Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [kxieem/kxieem.github.io#1]
# Issues
- The site doesn't have mobile view.
- The overflow-x is not set to hidden, might add that in `Style.css`
```css
body{
        overflow-x: hidden;
}
```
